import "./globals.css";
import { Inter } from "next/font/google";
// import Header from "./components/Header";
import Header1 from "./components/Header1";
import Footer from "./components/Footer";
import ScrollToTopButton from "./components/ScrollToTopButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

{
  /* <Header /> */
}

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>

//         <Header1 />
//         {children}
//         <ScrollToTopButton />

//         <Footer />
//       </body>
//     </html>
//   );
// }

// export default function RootLayout({ children }) {

// adding the async await fetch in layout.js means this data is now up one layer in the tree and can be shared when I navigate to other routes, ex: still have full name and composed content from the /routepage
export default async function RootLayout({ children }) {
  // const res = await fetch("https://api.github.com/repos/vercel/next.js");
  // const res = await fetch(
  //   "http://worldtimeapi.org/api/timezone/America/Chicago"
  // );
  // const data = await res.json();

  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <Header1 />
          {children}
          {/* <h1>{data.full_name}</h1> */}
          {/* <h1>{data.datetime}</h1> */}

          <ScrollToTopButton />
          <Footer />
        </body>
      </html>
    </>
  );
}
