import "./globals.css";
import { Inter } from "next/font/google";
// import Header from "./components/Header";
import Header1 from "./components/Header1";
import Footer from "./components/Footer";
import ScrollToTopButton from "./components/ScrollToTopButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        <Header1 />
        {children}
        <ScrollToTopButton />

        <Footer />
      </body>
    </html>
  );
}
