import "./globals.css";
import { Inter } from "next/font/google";
import Header1 from "./components/Header1";
import Footer from "./components/Footer";
import ScrollToTopButton from "./components/ScrollToTopButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pokemon Kids",
  description: "Generated by create next app",
};

// adding the async await fetch in layout.js means this data is now up one layer in the tree and can be shared when I navigate to other routes, ex: still have full name and composed content from the /routepage
export default async function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <Header1 />
          {children}
          <ScrollToTopButton />
          <Footer />
        </body>
      </html>
    </>
  );
}
